# FIXME: currently just builds it, eventually, should use qemu to try to run
# the image (potentially as a separate action)
name: build-prawnos-image

on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@master
      - name: build image
        run: docker run --mount type=bind,source=$PWD,target=/PrawnOS
             --privileged=true -v/dev:/dev debian:buster
             /bin/bash /PrawnOS/tests/build-image.sh "$GITHUB_SHA"
      - name: publish image
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: "PrawnOS-Shiba-c201-git-*.img"

      # These are needed for qemu emulation:
      - name: publish kernel
        uses: actions/upload-artifact@v2
        with:
          name: prawnos-kernel
          path: "./build/linux-*/vmlinux.kpart"
      # FIXME: Is this useful on its own?
      - name: publish c201p/veyron-speedy device tree binary (dtb)
        uses: actions/upload-artifact@v2
        with:
          name: c201p-veyron-speedy.dtb
          path: "./build/linux-*/arch/arm/boot/dts/rk3288-veyron-speedy.dtb"
      - name: bundle other dtbs
        uses: jjkaram/archive-action@v1.0.0
        with:
          #args: "tar -czvf dtbs-${GITHUB_SHA}.tar.gz ./build/linux-*/arch/arm/boot/dts/*.dtb"
          args: "find . -iname \\*.dtb"

      # FIXME: Not sure if this is useful or not (if above works)
      - name: publish all available device tree binary (dtb)
        uses: actions/upload-artifact@v2
        with:
          name: "all-dtbs"
          path: "dtbs-${GITHUB_SHA}.tar.gz"
